Moved prog check, so we can do color output

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,14 +1,5 @@
 #!/bin/sh
 
-for i in astyle cmake ctest diff make
-do
-    if ! type $i 2> /dev/null
-    then
-        echo "No '$i' found, please install or put it in PATH"
-        echo "You cannot commit"
-        exit 1
-    fi
-done
 
 p="$(pwd)"
 cd "$(git rev-parse --show-toplevel)"
@@ -43,6 +34,15 @@ die() {
     echo_red "$*"
     exit 1
 }
+
+for i in astyle cmake ctest diff make
+do
+    if ! type $i 2> /dev/null
+    then
+        echo_red "No '$i' found, please install or put it in PATH"
+        die "You cannot commit"
+    fi
+done
 
 echo_cyan "Starting test build"
 
